CREATE TABLE IF NOT EXISTS Clients (
  ClientID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL UNIQUE,
  Password VARCHAR(255) NOT NULL,
  Phone VARCHAR(15),
  Address TEXT
);

CREATE TABLE IF NOT EXISTS Trips (
  TripID INT AUTO_INCREMENT PRIMARY KEY,
  Destination VARCHAR(255) NOT NULL,
  Date DATE NOT NULL,
  Price DECIMAL(10, 2) NOT NULL,
  Description TEXT
);

CREATE TABLE IF NOT EXISTS Bookings (
  BookingID INT AUTO_INCREMENT PRIMARY KEY,
  ClientID INT NOT NULL,
  TripID INT NOT NULL,
  BookingDate DATE NOT NULL,
  Status VARCHAR(50) DEFAULT 'Pending',
  FOREIGN KEY (ClientID) REFERENCES Clients(ClientID),
  FOREIGN KEY (TripID) REFERENCES Trips(TripID)
);

CREATE TABLE IF NOT EXISTS Reviews (
  ReviewID INT AUTO_INCREMENT PRIMARY KEY,
  ClientID INT NOT NULL,
  TripID INT NOT NULL,
  Rating INT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
  Comment TEXT,
  FOREIGN KEY (ClientID) REFERENCES Clients(ClientID),
  FOREIGN KEY (TripID) REFERENCES Trips(TripID)
);

CREATE TABLE IF NOT EXISTS Notifications (
  NotificationID INT AUTO_INCREMENT PRIMARY KEY,
  ClientID INT NOT NULL,
  Message TEXT NOT NULL,
  SentDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ClientID) REFERENCES Clients(ClientID)
);

CREATE TABLE IF NOT EXISTS Admin (
  AdminID INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(255) NOT NULL UNIQUE,
  Password VARCHAR(255) NOT NULL
);